#ifndef SUBJECTS_H
#define SUBJECTS_H

#include <Arduino.h>

static const char* SUBJECTS[] = {

  // ─── Space & Astronomy ───
  "Black holes",
  "Neutron stars",
  "White dwarfs",
  "Supernovae",
  "Pulsars",
  "Quasars",
  "Dark matter",
  "Dark energy",
  "Cosmic background radiation",
  "Galaxy clusters",
  "Spiral galaxies",
  "Elliptical galaxies",
  "Nebulae",
  "Stellar nurseries",
  "Planetary rings",
  "Asteroid belts",
  "Comets",
  "Kuiper belt",
  "Oort cloud",
  "Exoplanets",
  "Rogue planets",
  "Binary star systems",
  "Red giants",
  "Solar wind",
  "Solar flares",
  "Sunspots",
  "Lunar craters",
  "Tidal locking",
  "Eclipses",
  "Meteor showers",
  "Cosmic rays",

  // ─── Physics & Chemistry ───
  "Quantum states",
  "Wave-particle duality",
  "Electromagnetic spectrum",
  "Radio waves",
  "Microwaves",
  "Infrared radiation",
  "Ultraviolet radiation",
  "X-rays",
  "Gamma rays",
  "Superconductivity",
  "Magnetism",
  "Electric fields",
  "Phase transitions",
  "Plasma",
  "Entropy",
  "Thermal equilibrium",
  "Brownian motion",
  "Fluid dynamics",
  "Surface tension",
  "Capillary action",
  "Crystal lattices",
  "Chemical bonds",
  "Isotopes",
  "Radioactivity",
  "Catalysts",
  "pH scale",
  "Oxidation",
  "Corrosion",
  "Polymer chains",

  // ─── Earth & Environment ───
  "Plate tectonics",
  "Volcanoes",
  "Earthquakes",
  "Fault lines",
  "Mountain ranges",
  "Ocean trenches",
  "Mid-ocean ridges",
  "Glaciers",
  "Ice caps",
  "Permafrost",
  "Deserts",
  "Sand dunes",
  "River deltas",
  "Watersheds",
  "Coral reefs",
  "Mangrove forests",
  "Rainforests",
  "Savannas",
  "Grasslands",
  "Wetlands",
  "Monsoons",
  "Trade winds",
  "Jet streams",
  "Cloud formations",
  "Ocean currents",
  "Tides",
  "Sea level rise",
  "Carbon cycle",
  "Nitrogen cycle",

  // ─── Biology & Life ───
  "DNA",
  "RNA",
  "Genes",
  "Chromosomes",
  "Cell membranes",
  "Mitochondria",
  "Photosynthesis",
  "Cell division",
  "Stem cells",
  "Microbiomes",
  "Bacteria",
  "Viruses",
  "Fungi",
  "Algae",
  "Protists",
  "Symbiosis",
  "Parasitism",
  "Evolution",
  "Natural selection",
  "Genetic drift",
  "Speciation",
  "Extinction events",
  "Bioluminescence",
  "Camouflage",
  "Regeneration",
  "Metamorphosis",
  "Hibernation",
  "Migration",
  "Ecosystems",

  // ─── Animals ───
  "Octopuses",
  "Crows",
  "Dolphins",
  "Elephants",
  "Wolves",
  "Ant colonies",
  "Termite mounds",
  "Honeybees",
  "Butterflies",
  "Jellyfish",
  "Axolotls",
  "Platypuses",
  "Bats",
  "Owls",
  "Penguins",
  "Sharks",
  "Whales",
  "Seahorses",
  "Frogs",
  "Chameleons",
  "Tardigrades",
  "Sloths",
  "Meerkats",
  "Horseshoe crabs",
  "Komodo dragons",

  // ─── Human Body & Mind ───
  "Human brain",
  "Neurons",
  "Synapses",
  "Neurotransmitters",
  "Memory",
  "Dreams",
  "Sleep cycles",
  "Circadian rhythm",
  "Muscle fibers",
  "Reflexes",
  "Pain perception",
  "Sensory adaptation",
  "Vision",
  "Hearing",
  "Balance",
  "Taste receptors",
  "Smell receptors",
  "Immune system",
  "Hormones",
  "Adrenaline",
  "Endorphins",
  "Placebo effect",
  "Body temperature regulation",

  // ─── Technology ───
  "Transistors",
  "Integrated circuits",
  "Microcontrollers",
  "Semiconductors",
  "Printed circuit boards",
  "Sensors",
  "Actuators",
  "Electric motors",
  "Batteries",
  "Capacitors",
  "Resistors",
  "LEDs",
  "Lasers",
  "Fiber optics",
  "Touchscreens",
  "Wireless communication",
  "Bluetooth",
  "Wi-Fi",
  "GPS",
  "Satellites",
  "Robotics",
  "Automation",
  "Machine learning",
  "Neural networks",
  "Artificial intelligence",

  // ─── Mathematics & Patterns ───
  "Prime numbers",
  "Fibonacci sequence",
  "Fractals",
  "Chaos theory",
  "Probability",
  "Statistics",
  "Topology",
  "Graph theory",
  "Golden ratio",
  "Symmetry",
  "Tessellations",
  "Randomness",
  "Algorithms",
  "Encryption",
  "Error correction",

  // ─── History & Civilization ───
  "Stone tools",
  "Bronze Age",
  "Iron Age",
  "Ancient Egypt",
  "Ancient Rome",
  "Ancient Greece",
  "Mesopotamia",
  "Indus Valley",
  "Mayan civilization",
  "Viking age",
  "Medieval cities",
  "Feudal systems",
  "Trade routes",
  "Silk Road",
  "Maritime navigation",
  "Cartography",
  "Printing press",
  "Mechanical clocks",
  "Gunpowder",
  "Industrial revolution",

  // ─── Culture & Society ───
  "Languages",
  "Writing systems",
  "Alphabets",
  "Symbols",
  "Mythology",
  "Folklore",
  "Rituals",
  "Music",
  "Rhythm",
  "Harmony",
  "Storytelling",
  "Oral traditions",
  "Art styles",
  "Architecture",
  "Monuments",
  "Calendars",
  "Timekeeping",
  "Games",
  "Puzzles",

  // ─── Everyday Curiosities ───
  "Mirrors",
  "Optical illusions",
  "Shadows",
  "Echoes",
  "Sound waves",
  "Light refraction",
  "Rainbows",
  "Static electricity",
  "Friction",
  "Pressure",
  "Vacuum",
  "Foam",
  "Bubbles",
  "Ice",
  "Steam",
  "Fire",
  "Smoke",
  "Rust",
  "Dust",
  "Sand"

};

inline String pickRandomSubject() {
  int count = sizeof(SUBJECTS) / sizeof(SUBJECTS[0]);
  return String(SUBJECTS[random(count)]);
}

#endif // SUBJECTS_H
